// ──────────────────────────────────────────
// SignalOS — Demo Data: Pre-seeded Historical Events
// ──────────────────────────────────────────

import { Signal, StockInfo, ConvergenceAlert } from './types';

// ── 15 Stocks ────────────────────────────

export const DEMO_STOCKS: StockInfo[] = [
  { name: 'Adani Enterprises', symbol: 'ADANIENT', sector: 'Infrastructure', currentPrice: 2847.30, priceChange: 42.15, priceChangePercent: 1.50, signalCount: 3, signals: [], hasConvergence: true },
  { name: 'Tata Motors', symbol: 'TATAMOTORS', sector: 'Automobile', currentPrice: 972.45, priceChange: 18.90, priceChangePercent: 1.98, signalCount: 3, signals: [], hasConvergence: true },
  { name: 'IRCTC', symbol: 'IRCTC', sector: 'Travel & Tourism', currentPrice: 894.55, priceChange: -12.30, priceChangePercent: -1.36, signalCount: 2, signals: [], hasConvergence: true },
  { name: 'Zomato', symbol: 'ZOMATO', sector: 'Consumer Tech', currentPrice: 265.80, priceChange: 8.45, priceChangePercent: 3.28, signalCount: 3, signals: [], hasConvergence: true },
  { name: 'Reliance Industries', symbol: 'RELIANCE', sector: 'Conglomerate', currentPrice: 2456.70, priceChange: -15.20, priceChangePercent: -0.62, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'Infosys', symbol: 'INFY', sector: 'IT Services', currentPrice: 1587.90, priceChange: 23.45, priceChangePercent: 1.50, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'HDFC Bank', symbol: 'HDFCBANK', sector: 'Banking', currentPrice: 1678.25, priceChange: -8.90, priceChangePercent: -0.53, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'TCS', symbol: 'TCS', sector: 'IT Services', currentPrice: 3856.40, priceChange: 12.70, priceChangePercent: 0.33, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'Bajaj Finance', symbol: 'BAJFINANCE', sector: 'NBFC', currentPrice: 7234.15, priceChange: 89.30, priceChangePercent: 1.25, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Asian Paints', symbol: 'ASIANPAINT', sector: 'Consumer', currentPrice: 2890.60, priceChange: -34.50, priceChangePercent: -1.18, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'ITC', symbol: 'ITC', sector: 'FMCG', currentPrice: 467.85, priceChange: 5.20, priceChangePercent: 1.12, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'SBI', symbol: 'SBIN', sector: 'Banking', currentPrice: 756.30, priceChange: 11.45, priceChangePercent: 1.54, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Sun Pharma', symbol: 'SUNPHARMA', sector: 'Pharma', currentPrice: 1234.90, priceChange: -7.60, priceChangePercent: -0.61, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'Wipro', symbol: 'WIPRO', sector: 'IT Services', currentPrice: 456.70, priceChange: 3.80, priceChangePercent: 0.84, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Bharti Airtel', symbol: 'BHARTIARTL', sector: 'Telecom', currentPrice: 1567.20, priceChange: 21.90, priceChangePercent: 1.42, signalCount: 1, signals: [], hasConvergence: false },
  { name: 'Hindustan Unilever', symbol: 'HINDUNILVR', sector: 'Consumer', currentPrice: 2450.00, priceChange: 12.40, priceChangePercent: 0.51, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'ICICI Bank', symbol: 'ICICIBANK', sector: 'Banking', currentPrice: 1080.00, priceChange: 15.20, priceChangePercent: 1.42, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Axis Bank', symbol: 'AXISBANK', sector: 'Banking', currentPrice: 1050.00, priceChange: -5.40, priceChangePercent: -0.51, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Kotak Mahindra Bank', symbol: 'KOTAKBANK', sector: 'Banking', currentPrice: 1780.00, priceChange: 8.90, priceChangePercent: 0.50, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Larsen & Toubro', symbol: 'LT', sector: 'Infrastructure', currentPrice: 3500.00, priceChange: 45.60, priceChangePercent: 1.32, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Maruti Suzuki', symbol: 'MARUTI', sector: 'Automobile', currentPrice: 12000.00, priceChange: 150.00, priceChangePercent: 1.27, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Mahindra & Mahindra', symbol: 'M&M', sector: 'Automobile', currentPrice: 1900.00, priceChange: 34.50, priceChangePercent: 1.85, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'UltraTech Cement', symbol: 'ULTRACEMCO', sector: 'Infrastructure', currentPrice: 9800.00, priceChange: -78.40, priceChangePercent: -0.79, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Titan Company', symbol: 'TITAN', sector: 'Consumer', currentPrice: 3600.00, priceChange: 23.10, priceChangePercent: 0.65, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'JSW Steel', symbol: 'JSWSTEEL', sector: 'Infrastructure', currentPrice: 850.00, priceChange: 12.30, priceChangePercent: 1.47, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Tata Steel', symbol: 'TATASTEEL', sector: 'Infrastructure', currentPrice: 150.00, priceChange: 2.10, priceChangePercent: 1.42, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Power Grid', symbol: 'POWERGRID', sector: 'Utilities', currentPrice: 280.00, priceChange: 4.50, priceChangePercent: 1.63, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'NTPC', symbol: 'NTPC', sector: 'Utilities', currentPrice: 340.00, priceChange: 5.80, priceChangePercent: 1.74, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'ONGC', symbol: 'ONGC', sector: 'Energy', currentPrice: 270.00, priceChange: -3.20, priceChangePercent: -1.17, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Coal India', symbol: 'COALINDIA', sector: 'Energy', currentPrice: 450.00, priceChange: 8.90, priceChangePercent: 2.02, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Grasim Industries', symbol: 'GRASIM', sector: 'Conglomerate', currentPrice: 2200.00, priceChange: 15.60, priceChangePercent: 0.71, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Hindalco Industries', symbol: 'HINDALCO', sector: 'Infrastructure', currentPrice: 580.00, priceChange: 12.40, priceChangePercent: 2.18, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Nestle India', symbol: 'NESTLEIND', sector: 'Consumer', currentPrice: 2500.00, priceChange: -34.50, priceChangePercent: -1.36, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Britannia Industries', symbol: 'BRITANNIA', sector: 'Consumer', currentPrice: 4900.00, priceChange: 56.70, priceChangePercent: 1.17, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Cipla', symbol: 'CIPLA', sector: 'Pharma', currentPrice: 1450.00, priceChange: 23.40, priceChangePercent: 1.64, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Dr. Reddys Laboratories', symbol: 'DRREDDY', sector: 'Pharma', currentPrice: 6200.00, priceChange: 89.10, priceChangePercent: 1.46, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Apollo Hospitals', symbol: 'APOLLOHOSP', sector: 'Healthcare', currentPrice: 6300.00, priceChange: 123.40, priceChangePercent: 2.00, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Divis Laboratories', symbol: 'DIVISLAB', sector: 'Pharma', currentPrice: 3700.00, priceChange: -45.60, priceChangePercent: -1.22, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Adani Ports', symbol: 'ADANIPORTS', sector: 'Infrastructure', currentPrice: 1300.00, priceChange: 21.30, priceChangePercent: 1.66, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Bajaj Auto', symbol: 'BAJAJ-AUTO', sector: 'Automobile', currentPrice: 8800.00, priceChange: 234.50, priceChangePercent: 2.74, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Bajaj Finserv', symbol: 'BAJAJFINSV', sector: 'NBFC', currentPrice: 1600.00, priceChange: 12.40, priceChangePercent: 0.78, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Eicher Motors', symbol: 'EICHERMOT', sector: 'Automobile', currentPrice: 4200.00, priceChange: 89.30, priceChangePercent: 2.17, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Hero MotoCorp', symbol: 'HEROMOTOCO', sector: 'Automobile', currentPrice: 4600.00, priceChange: -56.70, priceChangePercent: -1.22, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Bharat Petroleum', symbol: 'BPCL', sector: 'Energy', currentPrice: 600.00, priceChange: 12.30, priceChangePercent: 2.09, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'HCL Technologies', symbol: 'HCLTECH', sector: 'IT Services', currentPrice: 1650.00, priceChange: 34.50, priceChangePercent: 2.14, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Tech Mahindra', symbol: 'TECHM', sector: 'IT Services', currentPrice: 1300.00, priceChange: -12.40, priceChangePercent: -0.94, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'LTIMindtree', symbol: 'LTIM', sector: 'IT Services', currentPrice: 5200.00, priceChange: 78.40, priceChangePercent: 1.53, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'SBI Life Insurance', symbol: 'SBILIFE', sector: 'Insurance', currentPrice: 1500.00, priceChange: 21.30, priceChangePercent: 1.44, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'HDFC Life Insurance', symbol: 'HDFCLIFE', sector: 'Insurance', currentPrice: 630.00, priceChange: -8.90, priceChangePercent: -1.39, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'IndusInd Bank', symbol: 'INDUSINDBK', sector: 'Banking', currentPrice: 1480.00, priceChange: 34.50, priceChangePercent: 2.39, signalCount: 0, signals: [], hasConvergence: false },
  { name: 'Jio Financial Services', symbol: 'JIOFIN', sector: 'NBFC', currentPrice: 350.00, priceChange: 12.40, priceChangePercent: 3.67, signalCount: 0, signals: [], hasConvergence: false },
];

// ── Demo Signals ─────────────────────────

export const DEMO_SIGNALS: Signal[] = [
  // ── Adani Enterprises Convergence (3 signals in 5 days) ──
  {
    id: 'sig-adani-1',
    stock: 'Adani Enterprises',
    stockSymbol: 'ADANIENT',
    signalType: 'bulk_deal',
    date: '2024-01-15',
    timestamp: new Date('2024-01-15').getTime(),
    metadata: {
      description: 'GQG Partners acquired 1.2Cr shares at ₹2,680 per share in a single block deal worth ₹3,216Cr',
      dealSize: '₹3,216 Cr',
      buyerSeller: 'GQG Partners (Buyer)',
      priceAtSignal: 2680,
      volume: 12000000,
    },
    source: 'NSE Bulk Deals',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-adani-2',
    stock: 'Adani Enterprises',
    stockSymbol: 'ADANIENT',
    signalType: 'insider_trading',
    date: '2024-01-17',
    timestamp: new Date('2024-01-17').getTime(),
    metadata: {
      description: 'Promoter group entity acquired 45L shares through open market at ₹2,710 avg price',
      insiderName: 'S.B. Adani Family Trust',
      insiderDesignation: 'Promoter Group',
      transactionType: 'buy',
      value: 121950000,
      priceAtSignal: 2710,
    },
    source: 'SEBI SAST Disclosures',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-adani-3',
    stock: 'Adani Enterprises',
    stockSymbol: 'ADANIENT',
    signalType: 'news_sentiment',
    date: '2024-01-19',
    timestamp: new Date('2024-01-19').getTime(),
    metadata: {
      description: 'Multiple positive news articles about Adani groups new green energy partnerships and airport expansion deals',
      sentiment: 'positive',
      newsHeadline: 'Adani Green Energy bags 2GW solar project from SECI',
      newsSource: 'Economic Times, Moneycontrol',
    },
    source: 'Google News + AI Sentiment',
    lastSuccessTimestamp: Date.now(),
  },

  // ── Tata Motors Convergence (3 signals in 6 days) ──
  {
    id: 'sig-tata-1',
    stock: 'Tata Motors',
    stockSymbol: 'TATAMOTORS',
    signalType: 'technical_breakout',
    date: '2024-02-05',
    timestamp: new Date('2024-02-05').getTime(),
    metadata: {
      description: 'Stock broke above 200-day MA at ₹895 on 3.2x average volume, MACD crossover confirmed',
      maValue: 895,
      volumeMultiple: 3.2,
      priceAtSignal: 928,
    },
    source: 'Technical Analysis Engine',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-tata-2',
    stock: 'Tata Motors',
    stockSymbol: 'TATAMOTORS',
    signalType: 'insider_trading',
    date: '2024-02-07',
    timestamp: new Date('2024-02-07').getTime(),
    metadata: {
      description: 'CFO P.B. Balaji purchased 50,000 shares at ₹940 through employee stock option exercise and open market',
      insiderName: 'P.B. Balaji',
      insiderDesignation: 'CFO',
      transactionType: 'buy',
      value: 47000000,
      priceAtSignal: 940,
    },
    source: 'BSE Insider Disclosures',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-tata-3',
    stock: 'Tata Motors',
    stockSymbol: 'TATAMOTORS',
    signalType: 'news_sentiment',
    date: '2024-02-09',
    timestamp: new Date('2024-02-09').getTime(),
    metadata: {
      description: 'JLR quarterly earnings beat estimates by 18%, EV order book surges to record levels',
      sentiment: 'positive',
      newsHeadline: 'JLR posts record profits; Tata Motors EV bookings hit all-time high',
      newsSource: 'Bloomberg, Reuters',
    },
    source: 'Google News + AI Sentiment',
    lastSuccessTimestamp: Date.now(),
  },

  // ── IRCTC Convergence (2 signals in 4 days) ──
  {
    id: 'sig-irctc-1',
    stock: 'IRCTC',
    stockSymbol: 'IRCTC',
    signalType: 'bulk_deal',
    date: '2024-03-10',
    timestamp: new Date('2024-03-10').getTime(),
    metadata: {
      description: 'Government of India OFS — 5% stake sale at ₹850 floor price; oversubscribed 3.8x by institutional investors',
      dealSize: '₹4,250 Cr',
      buyerSeller: 'Govt of India (Seller) → Institutional Buyers',
      priceAtSignal: 850,
      volume: 40000000,
    },
    source: 'NSE Bulk Deals',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-irctc-2',
    stock: 'IRCTC',
    stockSymbol: 'IRCTC',
    signalType: 'technical_breakout',
    date: '2024-03-13',
    timestamp: new Date('2024-03-13').getTime(),
    metadata: {
      description: 'Post-OFS recovery: stock crossed 200-DMA resistance at ₹875 with 2.5x volume, RSI moved above 60',
      maValue: 875,
      volumeMultiple: 2.5,
      priceAtSignal: 892,
    },
    source: 'Technical Analysis Engine',
    lastSuccessTimestamp: Date.now(),
  },

  // ── Zomato Convergence (3 signals in 7 days) ──
  {
    id: 'sig-zomato-1',
    stock: 'Zomato',
    stockSymbol: 'ZOMATO',
    signalType: 'insider_trading',
    date: '2024-04-01',
    timestamp: new Date('2024-04-01').getTime(),
    metadata: {
      description: 'CEO Deepinder Goyal acquired 10L shares at ₹178 via ESOP exercise, first insider buy in 8 months',
      insiderName: 'Deepinder Goyal',
      insiderDesignation: 'CEO & Founder',
      transactionType: 'buy',
      value: 178000000,
      priceAtSignal: 178,
    },
    source: 'SEBI Insider Disclosures',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-zomato-2',
    stock: 'Zomato',
    stockSymbol: 'ZOMATO',
    signalType: 'news_sentiment',
    date: '2024-04-04',
    timestamp: new Date('2024-04-04').getTime(),
    metadata: {
      description: 'Blinkit achieves EBITDA breakeven for the first time; Goldman Sachs initiates coverage with a bull case of ₹310',
      sentiment: 'positive',
      newsHeadline: 'Blinkit turns EBITDA positive; analysts turn bullish on Zomato',
      newsSource: 'Moneycontrol, Livemint',
    },
    source: 'Google News + AI Sentiment',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-zomato-3',
    stock: 'Zomato',
    stockSymbol: 'ZOMATO',
    signalType: 'technical_breakout',
    date: '2024-04-06',
    timestamp: new Date('2024-04-06').getTime(),
    metadata: {
      description: 'Broke key resistance at ₹195 (52-week high zone) on 4.1x average volume, all moving averages aligned bullish',
      maValue: 195,
      volumeMultiple: 4.1,
      priceAtSignal: 212,
    },
    source: 'Technical Analysis Engine',
    lastSuccessTimestamp: Date.now(),
  },

  // ── Standalone signals (no convergence) ──
  {
    id: 'sig-reliance-1',
    stock: 'Reliance Industries',
    stockSymbol: 'RELIANCE',
    signalType: 'news_sentiment',
    date: '2024-03-20',
    timestamp: new Date('2024-03-20').getTime(),
    metadata: {
      description: 'Jio Financial Services demerger completes; separate listing drives mixed analyst views',
      sentiment: 'neutral',
      newsHeadline: 'Jio Financial lists separately after demerger from Reliance',
      newsSource: 'Economic Times',
    },
    source: 'Google News + AI Sentiment',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-infy-1',
    stock: 'Infosys',
    stockSymbol: 'INFY',
    signalType: 'insider_trading',
    date: '2024-02-20',
    timestamp: new Date('2024-02-20').getTime(),
    metadata: {
      description: 'Board member sold 25,000 shares at ₹1,560 as part of pre-planned trading program',
      insiderName: 'Board Member',
      insiderDesignation: 'Independent Director',
      transactionType: 'sell',
      value: 39000000,
      priceAtSignal: 1560,
    },
    source: 'BSE Insider Disclosures',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-tcs-1',
    stock: 'TCS',
    stockSymbol: 'TCS',
    signalType: 'technical_breakout',
    date: '2024-03-05',
    timestamp: new Date('2024-03-05').getTime(),
    metadata: {
      description: 'Briefly crossed 200-DMA but failed to sustain; volume was 1.4x average — weak breakout',
      maValue: 3800,
      volumeMultiple: 1.4,
      priceAtSignal: 3812,
    },
    source: 'Technical Analysis Engine',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-asian-1',
    stock: 'Asian Paints',
    stockSymbol: 'ASIANPAINT',
    signalType: 'news_sentiment',
    date: '2024-01-25',
    timestamp: new Date('2024-01-25').getTime(),
    metadata: {
      description: 'Crude oil price rise raises input cost concerns; Q3 margin guidance cut by management',
      sentiment: 'negative',
      newsHeadline: 'Asian Paints warns of margin pressure from rising crude oil prices',
      newsSource: 'CNBC-TV18',
    },
    source: 'Google News + AI Sentiment',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-sun-1',
    stock: 'Sun Pharma',
    stockSymbol: 'SUNPHARMA',
    signalType: 'bulk_deal',
    date: '2024-02-12',
    timestamp: new Date('2024-02-12').getTime(),
    metadata: {
      description: 'Foreign portfolio investor sold 28L shares at ₹1,220 in block deal',
      dealSize: '₹341 Cr',
      buyerSeller: 'FPI (Seller)',
      priceAtSignal: 1220,
      volume: 2800000,
    },
    source: 'NSE Bulk Deals',
    lastSuccessTimestamp: Date.now(),
  },
  {
    id: 'sig-airtel-1',
    stock: 'Bharti Airtel',
    stockSymbol: 'BHARTIARTL',
    signalType: 'insider_trading',
    date: '2024-03-18',
    timestamp: new Date('2024-03-18').getTime(),
    metadata: {
      description: 'Key management personnel acquired 15,000 shares at market price ₹1,480',
      insiderName: 'Gopal Vittal',
      insiderDesignation: 'MD & CEO (India & South Asia)',
      transactionType: 'buy',
      value: 22200000,
      priceAtSignal: 1480,
    },
    source: 'BSE Insider Disclosures',
    lastSuccessTimestamp: Date.now(),
  },
];

// ── Pre-computed Convergence Alerts ───────

export const DEMO_ALERTS: ConvergenceAlert[] = [
  {
    id: 'alert-adani-conv',
    stock: 'Adani Enterprises',
    stockSymbol: 'ADANIENT',
    signals: DEMO_SIGNALS.filter(s => s.stockSymbol === 'ADANIENT'),
    signalTypes: ['bulk_deal', 'insider_trading', 'news_sentiment'],
    timestamps: [
      new Date('2024-01-15').getTime(),
      new Date('2024-01-17').getTime(),
      new Date('2024-01-19').getTime(),
    ],
    windowStart: '2024-01-15',
    windowEnd: '2024-01-19',
    confidenceScore: 92,
    aiSummary: 'GQG Partners executed a ₹3,216Cr block acquisition while the Adani promoter group simultaneously increased holdings through open-market purchases, both within a 48-hour window. This dual institutional-plus-promoter accumulation pattern has historically preceded 15–25% rallies in Adani group stocks, as seen in the post-Hindenburg recovery phase where similar convergence preceded a 40% recovery over 60 trading sessions.',
    createdAt: new Date('2024-01-19').getTime(),
    status: 'active',
  },
  {
    id: 'alert-tata-conv',
    stock: 'Tata Motors',
    stockSymbol: 'TATAMOTORS',
    signals: DEMO_SIGNALS.filter(s => s.stockSymbol === 'TATAMOTORS'),
    signalTypes: ['technical_breakout', 'insider_trading', 'news_sentiment'],
    timestamps: [
      new Date('2024-02-05').getTime(),
      new Date('2024-02-07').getTime(),
      new Date('2024-02-09').getTime(),
    ],
    windowStart: '2024-02-05',
    windowEnd: '2024-02-09',
    confidenceScore: 88,
    aiSummary: 'Tata Motors broke above its 200-day moving average on 3.2x volume while the CFO made a significant open-market purchase of 50,000 shares, coinciding with JLR\'s record earnings beat of 18% above consensus. In the 2020–2023 period, Tata Motors showed similar triple-convergence patterns three times, each followed by a 20–35% move within the subsequent 90 trading days.',
    createdAt: new Date('2024-02-09').getTime(),
    status: 'active',
  },
  {
    id: 'alert-irctc-conv',
    stock: 'IRCTC',
    stockSymbol: 'IRCTC',
    signals: DEMO_SIGNALS.filter(s => s.stockSymbol === 'IRCTC'),
    signalTypes: ['bulk_deal', 'technical_breakout'],
    timestamps: [
      new Date('2024-03-10').getTime(),
      new Date('2024-03-13').getTime(),
    ],
    windowStart: '2024-03-10',
    windowEnd: '2024-03-13',
    confidenceScore: 76,
    aiSummary: 'The Government of India\'s 5% OFS was oversubscribed 3.8x by institutional investors at ₹850, followed by a swift recovery above the 200-DMA on 2.5x volume within three trading sessions. Historically, government OFS events in monopoly PSU stocks like IRCTC that see 3x+ oversubscription have led to price recoveries within 10 trading days in 7 out of 9 instances since 2019.',
    createdAt: new Date('2024-03-13').getTime(),
    status: 'active',
  },
  {
    id: 'alert-zomato-conv',
    stock: 'Zomato',
    stockSymbol: 'ZOMATO',
    signals: DEMO_SIGNALS.filter(s => s.stockSymbol === 'ZOMATO'),
    signalTypes: ['insider_trading', 'news_sentiment', 'technical_breakout'],
    timestamps: [
      new Date('2024-04-01').getTime(),
      new Date('2024-04-04').getTime(),
      new Date('2024-04-06').getTime(),
    ],
    windowStart: '2024-04-01',
    windowEnd: '2024-04-06',
    confidenceScore: 85,
    aiSummary: 'CEO Deepinder Goyal\'s first insider acquisition in 8 months coincided with Blinkit achieving EBITDA breakeven and a subsequent 52-week high breakout on 4.1x volume. In the Indian new-age tech sector, CEO open-market purchases followed by profitability milestones have preceded 30–50% re-ratings in 4 out of 5 comparable cases, including Paytm and PB Fintech\'s similar inflection points.',
    createdAt: new Date('2024-04-06').getTime(),
    status: 'active',
  },
];

// Map signals back to stocks
DEMO_STOCKS.forEach(stock => {
  stock.signals = DEMO_SIGNALS.filter(s => s.stockSymbol === stock.symbol);
  stock.signalCount = stock.signals.length;
  stock.hasConvergence = DEMO_ALERTS.some(a => a.stockSymbol === stock.symbol);
});
